### ISSUE TITLE
Add the option to invert DTR/RTS signals

### ISSUE THREAD

**Issue by me21** [themadinventor/esptool#137]
Please add the option to invert DTR/RTS signals (both or separately) in ESPROM.connect.
Currently, the code looks strange at the first sight:

```
# issue reset-to-bootloader:
# RTS = either CH_PD or nRESET (both active low = chip in reset)
# DTR = GPIO0 (active low = boot to flasher)
self._port.setDTR(False)
self._port.setRTS(True)  # <-- Why True? put the chip out of reset?
time.sleep(0.05)
self._port.setDTR(True)
self._port.setRTS(False)  # <-- Why False? put the chip in reset?
time.sleep(0.05)
self._port.setDTR(False)
```

because it seems that chip will be in reset after that sequence.
Apparently, the code expects that actual value of RTS line is the inversion of the passed value.
I've found that some USB-COM converters (i.e. FTDI) do invert RTS line, and the code will work with them. But this does not cover all usage variants. I use Microchip PIC18F14K50 microcontroller with USB CDC Serial Emulator code from Microchip to connect to ESP, and it does not invert RTS internally. I had to slightly change the firmware.
It would be better to add arguments "--invert-dtr" and "--invert-rts" with the former disabled by default and the latter enabled by default to keep the default behaviour the same while making esptool more versatile.

**Comment by projectgus** [comment]
Hi,

Thanks for the comprehensive explanation of what you're seeing.

It sounds like there's something unusual about the USB CDC firmware you have. In TTL serial, both RTS and DTR are "active-low" signals.

This means, when the signal is asserted (logic 1 ie True) the voltage on the pin is pulled to 0V. When the signal is de-asserted (logic 0 ie False) the voltage on the pin is 3.3V.

TTL Serial is not codified in a standard (I think it derives from the EIA-232/RS-232 standard, where 0="space"=+12V and 1="mark"=-12V, and the RS-232 hardware control signals are also inverted from these bit signalling levels). However you'll find the same "data signals are active high, control signals are active low" scheme is used across almost all hardware TTL serial peripherals, and definitely all common hardware USB/TTL adapters (FTDI, Cypress, Prolific, CH3xx, Microchip, etc.).

The reset sequence code looks funny at first, and could probably be commented better, but it is:

* setDTR(False) - deassert DTR - 3.3V on pin - GPIO0 goes high
* setRTS(True) - assert RTS - 0V on pin - chip pulled into reset
* delay (ensure chip is actually in reset)
* setDTR(True) - assert DTR - 0V on pin - GPIO0 pulled low (to select UART bootloader)
* setRTS(False) - deassert RTS - 3.3V on pin - chip let out of reset
* delay (allow the chip initialisation to read the GPIO0 signal and select the UART bootloader)
* setDTR(False) - deassert DTR - 3.3V on pin - GPIO0 goes back to 3.3V, same as initial state

The reason for the unnecessary-seeming additional DTR transitions is that some ESP hardware uses a [reset circuit originally designed into the nodemcu dev boards](https://raw.githubusercontent.com/nodemcu/nodemcu-devkit/master/Documents/NODEMCU_DEVKIT_SCH_BIG.png) where a pair of transistors are used to keep GPIO0 & RST as-is when both RTS=True && DTR=True, so that "normal" serial programs (that assert both control lines by default) won't hold the chip in reset. These transitions aren't strictly necessary for the simpler "wire RTS to RST & DTR to GPIO0" scheme, but they don't hurt.

I'm not entirely opposed to adding reset configuration options, but in this case it sounds to me like Microchip got their PIC USB-CDC firmware wrong (even their MCP2xxxx series of USB/TTL adapters use active low control signalling). So probably better to fix it in the firmware.
