### ISSUE TITLE
Flash > 512k ???

### ISSUE THREAD

**Issue by 3s1d** [themadinventor/esptool#14]
Hi
I'm using an Olimex Dev Board which has a W25Q16BVSSIG (64Mbit aka 2MB) flash on-board. 
(see https://www.olimex.com/Products/Modules/Ethernet/MOD-WIFI-ESP8266-DEV/open-source-hardware#)

I currently playing around with the lua-nodemcu-firmware (see https://github.com/nodemcu/nodemcu-firmware). The firmware uses the free flash memory as a filesystem. However, each time the firmware tries to access an area above 512k it fails. But only if I use this tool for the upload process. If I use the original provided one (http://bbs.espressif.com/viewtopic.php?f=7&t=25) and upload the SAME bins at the same locations, everything works fine...

Regards,
Juergen

**Comment by themadinventor** [comment]
Espressif forked esptool for their python-based flashing tool. I haven't checked what changes they have done to the protocol code, but they are of course in a much better position of fixing bugs as they have the source of the bootloader ROM. I don't have a 64Mbit module at hand but I'll have a close look at what  Espressif have done when I'm back from my vacation.

**Comment by 3s1d** [comment]
As a side note: I was only able to verify that for a 32Mbit flash size. The "original" tool only gives size options of up to 32Mbit.

Thanks for investigating that.

**Comment by layerzerolabs** [comment]
I've also had the problem of not being able to successfully flash firmware onto my olimex board - I needed to use the nodemcu-flasher tool to do this. It would be great if this tool was able to deal with other flash sizes so that I could use a fully linux-based toolchain. Keep up the good inventing!

**Comment by themadinventor** [comment]
Status update: I've ordered an Olimex board to test on. Hopefully I'll figure this out by the end of the week or so. (PR:s are of course appreciated if anyone have solved it already ;) )

**Comment by hamishcunningham** [comment]
That would be great, thanks!

**Comment by themadinventor** [comment]
Sorry about the delay.

I believe this bug is now completely fixed by 41dba2047d97b036f406f8561fd082465c4cfefb. The trick is apparently to update the header in the binary blob that specifies the flash chip size.

Previous versions of esptool only set this field in `elf2image`, whereas Espressif's fork updated the binary on the fly when flashing. This behaviour is now also implemented in esptool.

The user-facing change is to specify the `-fs [size]` option when running `write_flash`. Note that the flash size is specified in Mbits, so flashing NodeMCU to a 2 MiB Olimex module is

`esptool.py write_flash -fs 16m 0 nodemcu_20150127.bin`

Also, it might perhaps help the NodeMCU firmware to perform a chip erase (`esptool.y erase_flash`) before flashing, and/or do a `file.format` in the lua shell.

I'll add all this to the readme asap.
Thank you for your feedback and patience and for your interest in esptool! :)

**Comment by themadinventor** [comment]
I'll close this for now; just write a note if you experience any problems.

**Comment by hamishcunningham** [comment]
That worked for me -- thanks!
H

**Comment by kfricke** [comment]
@themadinventor , just an off-topic question: I am having problems to boot the ESP board you mentioned from Olimex into UART mode. Could you try to describe what you did in a few words? Thanks!

**Comment by hamishcunningham** [comment]
you can just about see the wiring you need here:
https://pi.gate.ac.uk/images/esp/olimex-plus-dil-switch.jpg

and there's a bit of explanation here:
https://github.com/hamishcunningham/fishy-wifi#develop

hth
h

On 10 February 2015 at 00:12, kfricke <notifications@github.com> wrote:

> @themadinventor <https://github.com/themadinventor> , just an off-topic
> question: I am having problems to boot the ESP board you mentioned from
> Olimex into UART mode. Could you try to describe what you did in a few
> words? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/themadinventor/esptool/issues/14#issuecomment-73619251>
> .
>



-- 

*Hamish Cunningham*
Professor of Computer Science, University of Sheffield, UK
+44 7920 765 455  http://twitter.com/@HCunningham  hamish@gate.ac.uk
http://pi.gate.ac.uk    http://hamish.gate.ac.uk   http://gate.ac.uk

**Comment by kfricke** [comment]
I have followed the instructions and schematics by Olimex already which make most parts you mention obvious. So i am just searching for reasons why my flashing attempt to the Olimex board does fail.

Regarding your documentation there, i did comment on it. Some things are a not that well described imho.

**Comment by kfricke** [comment]
I have been successful flashing my Olimex board. My FTDI programmer was the fault.
