### ISSUE TITLE
SPIFFS.begin() Returns False after Flashing ESP8266

### ISSUE THREAD

**Issue by craigfoo** [themadinventor/esptool#142]
I'm developing on a ESP-12E module from AI-Thinker using the Eclipse IDE with platform.io which uses esptool to flash the ESP8266. I've had great success with this setup.

Now, I'm trying to flash the module via the terminal using:

`sudo esptool.py -p /dev/ttyAMA0 -b 115200 write_flash 0x00000000 firmware.bin`

Everything seems to work smoothly but in my program (I'm using the Arduino framework for programming), all SPIFFS operations aren't working right. SPIFFS.begin() returns false which doesn't allow me to do anything else useful with the file system. I'm assuming SPIFFS is just the SPI interface to the talk to the flash on the module. 

I'm not sure the difference between what platform.io is doing through Eclipse vs. what I'm doing on the terminal. Is there a command I'm missing that needs to boot the ESP back up in a special way?

To enter boot mode, I'm holding GPIO0 low, then pulsing reset.

**Comment by projectgus** [comment]
I'm sorry but I don't know anything about platform.io, so you may have more success looking for documentation or help with their flashing process so you can reproduce it (or fish around in their code/output to figure out what files it's flashing where).

It sounds like at mimimum the firmware.bin file is flashing correctly, or your program wouldn't be running.

My guess is that there's a second SPIFFS image file that is generated as part of the build process and needs to be flashed at a certain address in the flash, so that SPIFFs.begin() will find it. You can add additional address(es) and filename(s) to the esptool.py write_flash command line that you posted.

Sorry I can't be more helpful, but this is really outside the scope of esptool.py's functionality.
